/**
 * DailyDock — Premium Themes
 */

import { type ThemeColors, lightColors, darkColors, palette } from './colors';

export interface PremiumTheme {
  id: string;
  name: string;
  colors: ThemeColors;
}

export const premiumThemes: PremiumTheme[] = [
  {
    id: 'frutiger-aero',
    name: 'Frutiger Aero',
    colors: {
      ...lightColors,
      background: '#E0F7FA',
      surface: '#FFFFFF',
      surfaceElevated: '#FFFFFF',
      primary: '#00B4D8',
      primaryLight: '#CAF0F8',
      primaryDark: '#0077B6',
      borderFocused: '#00B4D8',
      gradientStart: '#90E0EF',
      gradientEnd: '#00B4D8',
      categoryPersonal: '#0077B6',
      categoryWork: '#03045E',
      categorySchool: '#00B4D8',
      categoryHealth: '#90E0EF',
      categoryShopping: '#CAF0F8',
      categoryCustom: '#0096C7',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    colors: {
      ...darkColors,
      background: '#09090B',
      surface: '#18181B',
      surfaceElevated: '#27272A',
      primary: '#A855F7',
      primaryLight: 'rgba(168, 85, 247, 0.15)',
      primaryDark: '#9333EA',
      gradientStart: '#C084FC',
      gradientEnd: '#9333EA',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean Deep',
    colors: {
      ...darkColors,
      background: '#0F172A',
      surface: '#1E293B',
      surfaceElevated: '#334155',
      primary: '#38BDF8',
      primaryLight: 'rgba(56, 189, 248, 0.15)',
      primaryDark: '#0284C7',
      gradientStart: '#7DD3FC',
      gradientEnd: '#0284C7',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    colors: {
      ...lightColors,
      background: '#F0FDF4',
      surface: '#FFFFFF',
      primary: '#22C55E',
      primaryLight: '#DCFCE7',
      primaryDark: '#16A34A',
      gradientStart: '#4ADE80',
      gradientEnd: '#16A34A',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    colors: {
      ...lightColors,
      background: '#FFF7ED',
      surface: '#FFFFFF',
      primary: '#F97316',
      primaryLight: '#FFEDD5',
      primaryDark: '#EA580C',
      gradientStart: '#FB923C',
      gradientEnd: '#EA580C',
    },
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    colors: {
      ...darkColors,
      background: '#000000',
      surface: '#111111',
      surfaceElevated: '#222222',
      primary: '#FDE047',
      primaryLight: 'rgba(253, 224, 71, 0.15)',
      primaryDark: '#EAB308',
      textPrimary: '#FDE047',
      textSecondary: '#D9F99D',
      gradientStart: '#FEF08A',
      gradientEnd: '#EAB308',
    },
  },
  {
    id: 'lavender',
    name: 'Lavender',
    colors: {
      ...lightColors,
      background: '#FAF5FF',
      surface: '#FFFFFF',
      primary: '#A855F7',
      primaryLight: '#F3E8FF',
      primaryDark: '#9333EA',
      gradientStart: '#C084FC',
      gradientEnd: '#9333EA',
    },
  },
  {
    id: 'mint',
    name: 'Mint Breeze',
    colors: {
      ...lightColors,
      background: '#ECFDF5',
      surface: '#FFFFFF',
      primary: '#10B981',
      primaryLight: '#D1FAE5',
      primaryDark: '#059669',
      gradientStart: '#34D399',
      gradientEnd: '#059669',
    },
  },
  {
    id: 'cherry',
    name: 'Cherry Blossom',
    colors: {
      ...lightColors,
      background: '#FFF1F2',
      surface: '#FFFFFF',
      primary: '#F43F5E',
      primaryLight: '#FFE4E6',
      primaryDark: '#E11D48',
      gradientStart: '#FB7185',
      gradientEnd: '#E11D48',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    colors: {
      ...darkColors,
      background: '#2E3440',
      surface: '#3B4252',
      surfaceElevated: '#434C5E',
      primary: '#88C0D0',
      primaryLight: 'rgba(136, 192, 208, 0.15)',
      primaryDark: '#5E81AC',
      textPrimary: '#ECEFF4',
      textSecondary: '#E5E9F0',
      textTertiary: '#D8DEE9',
      gradientStart: '#8FBCBB',
      gradientEnd: '#5E81AC',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    colors: {
      ...darkColors,
      background: '#282A36',
      surface: '#44475A',
      surfaceElevated: '#6272A4',
      primary: '#FF79C6',
      primaryLight: 'rgba(255, 121, 198, 0.15)',
      primaryDark: '#BD93F9',
      textPrimary: '#F8F8F2',
      gradientStart: '#FF79C6',
      gradientEnd: '#BD93F9',
    },
  },
  {
    id: 'synthwave',
    name: 'Synthwave',
    colors: {
      ...darkColors,
      background: '#2B213A',
      surface: '#241B2F',
      surfaceElevated: '#262335',
      primary: '#FF7EDB',
      primaryLight: 'rgba(255, 126, 219, 0.15)',
      primaryDark: '#F92AAD',
      textPrimary: '#F8F8F2',
      gradientStart: '#36F9F6',
      gradientEnd: '#FF7EDB',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    colors: {
      ...darkColors,
      background: '#272822',
      surface: '#3E3D32',
      surfaceElevated: '#49483E',
      primary: '#A6E22E',
      primaryLight: 'rgba(166, 226, 46, 0.15)',
      primaryDark: '#E6DB74',
      textPrimary: '#F8F8F2',
      gradientStart: '#A6E22E',
      gradientEnd: '#66D9EF',
    },
  },
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    colors: {
      ...darkColors,
      background: '#191724',
      surface: '#1F1D2E',
      surfaceElevated: '#26233A',
      primary: '#EBBCBA',
      primaryLight: 'rgba(235, 188, 186, 0.15)',
      primaryDark: '#31748F',
      textPrimary: '#E0DEF4',
      textSecondary: '#908CAA',
      gradientStart: '#F6C177',
      gradientEnd: '#EBBCBA',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    colors: {
      ...darkColors,
      background: '#1A1B26',
      surface: '#24283B',
      surfaceElevated: '#414868',
      primary: '#7AA2F7',
      primaryLight: 'rgba(122, 162, 247, 0.15)',
      primaryDark: '#2AC3DE',
      textPrimary: '#C0CAF5',
      gradientStart: '#BB9AF7',
      gradientEnd: '#7AA2F7',
    },
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    colors: {
      ...darkColors,
      background: '#002B36',
      surface: '#073642',
      surfaceElevated: '#586E75',
      primary: '#2AA198',
      primaryLight: 'rgba(42, 161, 152, 0.15)',
      primaryDark: '#268BD2',
      textPrimary: '#839496',
      gradientStart: '#2AA198',
      gradientEnd: '#859900',
    },
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    colors: {
      ...darkColors,
      background: '#282828',
      surface: '#3C3836',
      surfaceElevated: '#504945',
      primary: '#FABD2F',
      primaryLight: 'rgba(250, 189, 47, 0.15)',
      primaryDark: '#D79921',
      textPrimary: '#EBDBB2',
      gradientStart: '#B8BB26',
      gradientEnd: '#FABD2F',
    },
  },
  {
    id: 'cobalt',
    name: 'Cobalt',
    colors: {
      ...darkColors,
      background: '#002240',
      surface: '#002D54',
      surfaceElevated: '#003A68',
      primary: '#FFC600',
      primaryLight: 'rgba(255, 198, 0, 0.15)',
      primaryDark: '#FF9D00',
      textPrimary: '#FFFFFF',
      gradientStart: '#FFC600',
      gradientEnd: '#FF9D00',
    },
  },
  {
    id: 'sepia',
    name: 'Sepia',
    colors: {
      ...lightColors,
      background: '#F4ECD8',
      surface: '#FAF3E0',
      surfaceElevated: '#FFF8E7',
      primary: '#5B4636',
      primaryLight: '#A39171',
      primaryDark: '#3D2B1F',
      textPrimary: '#433422',
      gradientStart: '#A39171',
      gradientEnd: '#5B4636',
    },
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    colors: {
      ...darkColors,
      background: '#1A0B2E',
      surface: '#2D1B4E',
      surfaceElevated: '#432C7A',
      primary: '#00FFCC',
      primaryLight: 'rgba(0, 255, 204, 0.15)',
      primaryDark: '#FF00CC',
      textPrimary: '#FFFFFF',
      gradientStart: '#00FFCC',
      gradientEnd: '#FF00CC',
    },
  },
];
